# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# OLED options

# Peripheral
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=n
# Animation FPS
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=960 
  # 60 frames per second
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=1920 
  # 30 frames per second
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=3600 
  # 16 frames per second
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=14400 
  # 4 frames per second
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=57600 
  # 1 frame per second

# Central
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE_MAX=100
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA_ANIMATION_MS=300
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT_ANIMATION_MS=300
CONFIG_NICE_OLED_WIDGET_RESPONSIVE=n
CONFIG_NICE_OLED_WIDGET_RESPONSIVE_BONGO_CAT=n
